name: Backend build and deploy 

on:
  push:
    branches: [ main ]
    paths:
      - packages/backend/**
  workflow_dispatch:
  
jobs:  
  build-and-deploy:
    name: "build and deploy"
    runs-on: ubuntu-latest
    env:
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_PORT: ${{ secrets.SSH_PORT }}
      HOST_PATH: ${{ secrets.HOST_PATH }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'
      - run: yarn install
      - run: yarn bootstrap
      - run: yarn lint
      - name: Create backend .env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_DB_HOST: ${{ secrets.DB_HOST }}
          envkey_DB_PORT: ${{ secrets.DB_PORT }}
          envkey_DB_USER: ${{ secrets.DB_USER }}
          envkey_DB_PW: ${{ secrets.DB_PW }}
          envkey_DB_DB: ${{ secrets.DB_DB }}
          envkey_PORT: 1368
          envkey_API_TOKEN_SECRET: ${{ secrets.API_TOKEN_SECRET }}
          envkey_API_TOKEN_REFRESH: ${{ secrets.API_TOKEN_REFRESH }}
          envkey_API_MAIL_KEY: ${{secrets.API_MAIL_KEY}}
          envkey_API_MAIL_SENDER: ${{secrets.API_MAIL_SENDER}}
          envkey_API_MAIL_DOMAIN: ${{secrets.API_MAIL_DOMAIN}}
          envkey_NODE_ENV: 'staging'
          directory: 'packages/backend/'
          file_name: .env
          fail_on_empty: false
          overwrite: true
      - name: Deploy backend .env file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: 'packages/backend/.env'
          target: '/var/www/store.rem029.com/'
          overwrite: true
      - run: yarn build:backend
      - name: Deploy backend
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: 'packages/backend/dist'
          target: '/var/www/store.rem029.com/'
          overwrite: true
      - name: Reload server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |            
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            PATH=$PATH:/${{secrets.SSH_USER}}/.npm-global/bin
            cd /var/www/store.rem029.com/
            npm i -g yarn
            git pull origin main
            source deploy.sh
