name: Frontend build and deploy 

on:
  push:
    branches: [ main ]
    paths:
      - packages/frontend/**
  workflow_dispatch:
  
jobs:  
  build-and-deploy:
    name: "build and deploy"
    runs-on: ubuntu-latest
    env:
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_PORT: ${{ secrets.SSH_PORT }}
      HOST_PATH: ${{ secrets.HOST_PATH }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'
      - run: yarn install
      - run: yarn bootstrap
      - run: yarn lint
      - name: Create frontend .env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_PORT: 1358
          envkey_REACT_APP_API_URL: "https://api.store.rem029.com"
          envkey_REACT_APP_APP_NAME: "store"
          envkey_REACT_APP_OPEN_WEATHER_API_KEY: ${{ secrets.OPEN_WEATHER_API_KEY }}
          directory: 'packages/frontend/'
          file_name: .env
          fail_on_empty: false
      - run: yarn build:frontend
      - name: Deploy frontend
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: 'packages/frontend/build'
          target: '/var/www/store.rem029.com/'
