name: Frontend run lint

on:
  pull_request:
      paths:
      - packages/frontend/**
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'
      - run: yarn install
      - run: cd packages/frontend/ && yarn lint
